DROP TABLE CONSUMER.PRODUCTS;
DROP DATABASE CONSUMER;

CREATE DATABASE CONSUMER;

CREATE TABLE CONSUMER.PRODUCTS
(
	PRODUCT_ID INT(4) AUTO_INCREMENT PRIMARY KEY,
	PRODUCT_NAME VARCHAR(60) NOT NULL,
	PRODUCT_DESC VARCHAR(250)
)ENGINE = INNODB;

INSERT INTO CONSUMER.PRODUCTS
(PRODUCT_NAME,PRODUCT_DESC)
VALUES
("PRODUCT1","PRODUCT DESCRIPTION 1");

INSERT INTO CONSUMER.PRODUCTS
(PRODUCT_NAME,PRODUCT_DESC)
VALUES
("PRODUCT2","PRODUCT DESCRIPTION 2");

INSERT INTO CONSUMER.PRODUCTS
(PRODUCT_NAME,PRODUCT_DESC)
VALUES
("PRODUCT3","PRODUCT DESCRIPTION 3");

INSERT INTO CONSUMER.PRODUCTS
(PRODUCT_NAME,PRODUCT_DESC)
VALUES
("PRODUCT4","PRODUCT DESCRIPTION 4");

INSERT INTO CONSUMER.PRODUCTS
(PRODUCT_NAME,PRODUCT_DESC)
VALUES
("PRODUCT5","PRODUCT DESCRIPTION 5");