-- DELETE ALL DATA FROM ALL THE TABLES
DELETE FROM EXAMPLE.USER_CREDENTIALS;
DELETE FROM EXAMPLE.USER_DETAILS;
DELETE FROM EXAMPLE.APP;

-- DELETE ALL THE CONSTRAINTS.
ALTER TABLE EXAMPLE.USER_CREDENTIALS
DROP FOREIGN KEY FK_USER_CREDENTILAS_CONSTRAINT_1;

ALTER TABLE EXAMPLE.USER_CREDENTIALS
DROP FOREIGN KEY FK_USER_CREDENTILAS_CONSTRAINT_2;

-- DELETE ALL THE TABLES BEFORE CREATING THE NEW TABLES.
DROP TABLE EXAMPLE.APP;
DROP TABLE EXAMPLE.USER_CREDENTIALS;
DROP TABLE EXAMPLE.USER_DETAILS;

-- CREATE ALL THE REQUIRED TABLES.

-- USER DETAILS TABLE TO STORE THE USER DETAILS.
CREATE TABLE EXAMPLE.USER_DETAILS
(
	USER_ID INT(4) AUTO_INCREMENT PRIMARY KEY,
	USER_NAME VARCHAR(60),
	USER_EMAIL VARCHAR(60)
)ENGINE = INNODB;

-- APP TABLE TO STORE ALL THE APP DETAILS.
CREATE TABLE EXAMPLE.APP
(
	APP_ID VARCHAR(100) AUTO_INCREMENT PRIMARY KEY,
	APP_NAME VARCHAR(50) UNIQUE NOT NULL,
	APP_DESCRIPTION VARCHAR(250),
	APP_SECRET VARCHAR(100) UNIQUE NOT NULL
	CALLBACK_URL VARCHAR(250)
)ENGINE = INNODB;

CREATE TABLE EXAMPLE.USER_CREDENTIALS
(
	USER_ID INT(4) PRIMARY KEY,
	USER_NAME VARCHAR(60) UNIQUE NOT NULL,
	PASSWORD VARCHAR(100)  NOT NULL
);


CREATE TABLE EXAMPLE.USER_ROLES
(
	USER_ID INT(4) PRIMARY KEY,
	USER_ROLE INT(4) NOT NULL
);

CREATE TABLE EXAMPLE.ROLES
(
	ROLE_ID INT(4) AUTO_INCREMENT PRIMARY KEY,
	ROLE_NAME VARCHAR(100) NOT NULL
)ENGINE = INNODB;

ALTER TABLE EXAMPLE.USER_CREDENTIALS
ADD CONSTRAINT FK_USER_CREDENTILAS_CONSTRAINT_1
FOREIGN KEY FK_USER_ID(USER_ID)
REFERENCES EXAMPLE.USER_DETAILS(USER_ID)
ON UPDATE CASCADE
ON DELETE RESTRICT;

ALTER TABLE EXAMPLE.USER_ROLES
ADD CONSTRAINT FK_USER_ROLES_CONSTRAINT_1
FOREIGN KEY FK_USER_ID(USER_ID)
REFERENCES EXAMPLE.USER_DETAILS(USER_ID)
ON UPDATE CASCADE
ON DELETE RESTRICT;

ALTER TABLE EXAMPLE.USER_ROLES
ADD CONSTRAINT FK_USER_ROLES_CONSTRAINT_2
FOREIGN KEY FK_USER_ROLE(USER_ROLE)
REFERENCES EXAMPLE.ROLES(ROLE_ID)
ON UPDATE CASCADE
ON DELETE RESTRICT;

INSERT INTO EXAMPLE.ROLES
(ROLE_NAME)
VALUES
("ROLE_ADMIN");

INSERT INTO EXAMPLE.ROLES
(ROLE_NAME)
VALUES
("ROLE_USER");

INSERT INTO EXAMPLE.ROLES
(ROLE_NAME)
VALUES
("ROLE_GUEST");

-- COMMIT ALL TRANSACTIONS.
COMMIT;