--DESCRIBE STATEMENTS
DESC EXAMPLE.USER_DETAILS;
DESC EXAMPLE.USER_CREDENTIALS;
DESC EXAMPLE.APP;

-- SELECT * STATEMENTS
SELECT * FROM EXAMPLE.USER_DETAILS;
SELECT * FROM EXAMPLE.USER_CREDENTIALS;
SELECT * FROM EXAMPLE.APP;

DESC APP;